#
# Config of SimpleCore
# Version: 0.1
#
config:
  # Enable or disable join or left messages
  join-message: true
  quit-message: true
  #
  # Basic format of chat with hover
  # and command action.
  # You can use placeholders of this plugin:
  # 1. "%displayName%" | Returns the modified name of the player.
  # 2. "%playerName%" | Returns alone default name of the player.
  #
  chat-format:
    enable: true
    # Enable or disable return display name with prefix of permissions plugins or directly vault plugin.
    displayname-with-prefix: true
    # Enable or disable return player name with prefix of permissions plugins or directly vault plugin.
    playername-with-prefix: true
    format:
      # You can use placeholders of the PlaceholderAPI plugin.
      chat-message: '%displayName% &b» &f'
      hover: '&eBasic hover to the format.'
      click-event: SUGGEST_COMMAND
      action: '/msg %player% '
#
# Enable or disable option of
# server list and edit messages.
#
server-list:
  enable: true
  respective-mode: false
  max-players: 100
  line1: '&bNoxus Team &8| &cEditable text'
  line2: '&7You can edit this in the config'
#
# Enable or disable sounds events.
#
# Please use sounds of this page:
# https://helpch.at/docs/1.8.8/org/bukkit/Sound.html
#
sounds:
  join-sound:
    enable: true
    sound: LEVEL_UP
    vol: 10
    pitch: 1
  broadcast-sound:
    enable: true
    sound: EXPLODE
    vol: 10
    pitch: 1
  message-sound:
    enable: true
    sound: CHICKEN_EGG_POP
    vol: 10
    pitch: 1