config:
  join-message: true
  quit-message: true
server-List:
  enable: true
  respective-mode: true
  max-players: 0
  line1: '&aMinecraft Server &8| &cTexto editable'
  line2: '&7En la config podras habilitar o deshabilitar'
titles:
  join-title:
    enable: true
    fade-in: 10
    stay: 15
    fade-out: 10