#
#   ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗
#  ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝
#  ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
#  ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
#  ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#   ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝
#
config:
  # Enable or disable join or left messages
  join-message: true
  quit-message: true
  #
  # Basic format of chat with hover
  # and command action.
  # You can use placeholders of this plugin:
  # 1. "%displayName%" | Returns the modified name of the player.
  # 2. "%playerName%" | Returns alone default name of the player.
  #
  chat-format:
    enable: true
    default:
      format:
        # You can use placeholders of the PlaceholderAPI plugin.
        chat-message: '%displayName% &b» &f'
        hover:
          - '&7This is a format default, please'
          - '&7don''t delete format.'
          - '&r'
          - '&eClick to send private message'
        click-event: SUGGEST_COMMAND
        action: '/msg %player% '
    groups:
      owner:
        format:
          # You can use placeholders of the PlaceholderAPI plugin.
          chat-message: '%displayName% &b» &c'
          hover:
            - '&bFormat to owner users.'
            - '&r'
            - '&eClick to send private message'
          click-event: SUGGEST_COMMAND
          action: '/msg %player% '
      vip:
        format:
          # You can use placeholders of the PlaceholderAPI plugin.
          chat-message: '%displayName% &b» &e'
          hover:
            - '&eYou''re the donator of this server'
            - '&r'
            - '&eClick to send private message'
          click-event: SUGGEST_COMMAND
          action: '/msg %player% '
  teleports:
    spawn:
      teleport-on-join: true
      spawn-time: 8
    warp-time: 6
#
# Enable or disable option of
# server list and edit messages.
#
server-list:
  enable: true
  respective-mode: false
  max-players: 100
  line1: '&bNoxus Team &8| &cEditable text'
  line2: '&7You can edit this in the config'
#
# Simple and easy system of private messages with
# hovers actions and hover text.
#
private-messages:
  sender:
    format:
      chat-message: '&8[&e*&8] &aYou to &c%target% &c» &f%message%'
      hover: '&eClick to send other message.'
      click-event: SUGGEST_COMMAND
      action: '/msg %target% '
  target:
    format:
      chat-message: '&8[&e*&8] &c%sender% &ato You &c» &f%message%'
      hover: '&eClick to send other message.'
      click-event: SUGGEST_COMMAND
      action: '/msg %sender% '
#
# Enable or disable sounds events.
#
# Please use sounds of this page:
# https://helpch.at/docs/1.8.8/org/bukkit/Sound.html
#
sounds:
  join-sound:
    enable: true
    sound: LEVEL_UP
    vol: 10
    pitch: 1
  broadcast-sound:
    enable: true
    sound: EXPLODE
    vol: 10
    pitch: 1
  message-sound:
    enable: true
    sound: CHICKEN_EGG_POP
    vol: 10
    pitch: 1