#
# Config of SimpleCore
# Version: 0.1
#
config:
  # Enable or disable join or left messages
  join-message: true
  quit-message: true
#
# Enable or disable option of
# server list and edit messages.
# You can use Placeholders in these messages.
#
server-list:
  enable: true
  respective-mode: true
  max-players: 0
  line1: '&aMinecraft Server &8| &cEditable text'
  line2: '&7You can edit this in the config'
#
# Enable or disable sounds events.
#
# Please use sounds of this page:
# https://helpch.at/docs/1.8.8/org/bukkit/Sound.html
#
sounds:
  join-sound:
    enable: true
    sound: ENDERDRAGON_GROWL
    vol: 10
    pitch: 1
  broadcast-sound:
    enable: true
    sound: ORB_PICKUP
    vol: 10
    pitch: 1