name: SimpleCore
version: ${project.version}
main: me.jonakls.simplecore.SimpleCore
authors: [Jonakls]
softdepend:
  - PlaceholderAPI
  - TitleAPI
commands:
  simplecore:
    description: General command of plugin
    aliases: [sc, simplec, score]
  gamemode:
    description: Gamemode generalized command option change
    aliases: [gm, game, mode]
  gmsp:
    description: Change gamemode to spectator mode
    aliases: [ spectator, gamesp, modesp ]
  gmc:
    description: Change gamemode to creative mode
    aliases: [ creative, gamec, modec ]
  gma:
    description: Change gamemode to adventure mode
    aliases: [ adventure, gamea, modea ]
  gms:
    description: Change gamemode to survival mode
    aliases: [ survival, games, modes ]
  flymode:
    description: Enable or disable flight in game
    aliases: [ fly, flight ]
  vanish:
    description: Enable or disable incognit mode of player
    aliases: [ v, vanish ]
  menu:
    description: Menu of options
    aliases: [ server ]
  fake:
    description: Send false messages of join, leave or custom
    aliases: [ fk, false ]
  broadcast:
    description: Send global message
    aliases: [ bc, announce ]
  stop:
    description: Command for stop the server with reason
    aliases: [ stp, reload, rl]