name: SimpleCore
version: ${project.version}
main: me.jonakls.simplecore.SimpleCore
authors: [Jonakls]
softdepend:
  - PlaceholderAPI
  - TitleAPI
commands:
  simplecore:
    description: Command general of plugin
    aliases: [sc, simplec, score]
  gamemode:
    description: Generalized command of gamemode option change
    aliases: [gm, game, mode]
  gmsp:
    description: Change gamemode to spectator mode
    aliases: [ spectator, gamesp, modesp ]
  gmc:
    description: Change gamemode to creative mode
    aliases: [ creative, gamec, modec ]
  gma:
    description: Change gamemode to adventure mode
    aliases: [ adventure, gamea, modea ]
  gms:
    description: Change gamemode to survival mode
    aliases: [ survival, games, modes ]
  flymode:
    description: Enable or disable flight in game
    aliases: [ fly, flight ]