name: SimpleCore
version: ${project.version}
main: me.jonakls.simplecore.SimpleCore
authors: [Jonakls]
softdepend:
  - PlaceholderAPI
  - Vault
commands:
  simplecore:
    description: General command of plugin
    aliases: [sc, simplec]
  gamemode:
    description: Gamemode generalized command option change
    aliases: [gm, game, mode]
  gmsp:
    description: Change gamemode to spectator mode
    aliases: [ spectator, gamesp, modesp ]
  gmc:
    description: Change gamemode to creative mode
    aliases: [ creative, gamec, modec ]
  gma:
    description: Change gamemode to adventure mode
    aliases: [ adventure, gamea, modea ]
  gms:
    description: Change gamemode to survival mode
    aliases: [ survival, games, modes ]
  flymode:
    description: Enable or disable flight in game
    aliases: [ fly, flight ]
  vanish:
    description: Enable or disable incognit mode of player
    aliases: [ v, vanish ]
  fake:
    description: Send false messages of join, leave or custom
    aliases: [ fk, false ]
  broadcast:
    description: Send global message
    aliases: [ bc, announce ]
  stop:
    description: Command for stop the server with reason
    aliases: [ stp, reload, rl]
  message:
    description: Send a private messages to players.
    aliases: [ msg, me, tell ]
  lag:
    description: Observe the performance of your server.
    aliases: [gc]
  nickname:
    description: Change you display name with custom colors.
    aliases: [nick]
  setwarp:
    description: Create a new warp ubication.
  warp:
    description: Go to a warp selected.
  delwarp:
    description: Delete the warp selected.
  time:
    description: Change the time in a world.
  day:
    description: Change to day un a world.
  night:
    description: Change to night in a world.
  midnight:
    description: Change to midnight in a world.
  sun:
    description: Change weather cycle to sun
  rain:
    description: Change weather cycle to rain
  thunder:
    description: Change weather cycle to thunder
  spawn:
    description: Go to spawn of server.
  setspawn:
    description: Define the spawn.
  delspawn:
    description: Delete current spawn.